# Generated by Django 5.0.6 on 2024-06-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=100)),
                ('RegisterNumber', models.IntegerField()),
                ('RollNumber', models.IntegerField()),
                ('Course', models.CharField(max_length=100)),
                ('Batch', models.CharField(max_length=100)),
            ],
        ),
    ]
