# Generated by Django 5.0.6 on 2024-06-12 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('StaffName', models.CharField(max_length=100)),
                ('StaffMail', models.EmailField(max_length=254)),
                ('StaffNumber', models.IntegerField()),
                ('staffReg_id', models.UUIDField(default=uuid.uuid4)),
                ('staffCourse', models.CharField(max_length=100)),
            ],
        ),
    ]
